# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0 # Verifique a versão mais recente
    hooks:
      - id: black
        name: blue
        args: ['--line-length=88'] # Configuração padrão do Blue

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0 # Verifique a versão mais recente
    hooks:
      - id: isort
        args: ['--profile', 'black'] # Compatível com Blue/Black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0 # Verifique a versão mais recente
    hooks:
      - id: flake8
        args: ['--max-line-length=88']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0 # Verifique a versão mais recente
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Verifique a versão mais recente
    hooks:
      - id: trailing-whitespace # Remove espaços em branco no final das linhas
      - id: end-of-file-fixer # Garante uma linha vazia no final do arquivo
      - id: check-yaml # Valida arquivos YAML
      - id: check-json # Valida arquivos JSON

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Verifique a versão mais recente
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500'] # Define um limite de 500 KB por arquivo

  - repo: https://github.com/pyupio/safety
    rev: v2.3.5 # Verifique a versão mais recente
    hooks:
      - id: safety
