repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run tests with pytest
        entry: poetry run task test
        language: system
        pass_filenames: false

      - id: blue
        name: Format code with Blue
        entry: poetry run blue
        language: system
        types: [python]
        args: ['--line-length=88']
        pass_filenames: true

      - id: isort
        name: Sort imports with isort
        entry: poetry run isort
        language: system
        types: [python]
        args: ['--profile', 'black'] # `blue` segue o mesmo padrão de `black`
        pass_filenames: true

      - id: flake8
        name: Lint code with Flake8
        entry: poetry run flake8
        language: system
        types: [python]
        args: ['--max-line-length=88']
        pass_filenames: true

      - id: mypy
        name: Type check with MyPy
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: true

      # - id: safety
      #   name: Check dependencies for security issues
      #   entry: poetry run safety check --full-report --file=requirements.txt --file=requirements_dev.txt
      #   language: system
      #   pass_filenames: false

      - id: check-added-large-files
        name: Prevent large files in repo
        entry: >
          poetry run python -c "import sys, os;
          [print(f'File too large: {f}') or sys.exit(1) for f in sys.argv[1:] if os.path.getsize(f) > 500 * 1024]"
        language: system
        pass_filenames: true

      - id: bandit
        name: Security analysis with Bandit
        entry: poetry run bandit -r src/
        language: system
        pass_filenames: false

      - id: detect-secrets
        name: Detect secrets in code
        entry: poetry run detect-secrets-hook --baseline .secrets.baseline || poetry run detect-secrets scan > .secrets.baseline
        language: system
        pass_filenames: false

      - id: debug-statements
        name: Remove debug statements (print, pdb)
        entry: poetry run flake8 --select=T20
        language: system
        pass_filenames: true
