repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run tests with pytest
        entry: poetry run task test
        language: system
        pass_filenames: false

      - id: blue
        name: Format code with Blue
        entry: poetry run blue
        language: system
        types: [python]
        args: ['--line-length=88']

      - id: isort
        name: Sort imports with isort
        entry: poetry run isort
        language: system
        types: [python]
        args: ['--profile', 'black'] # `blue` segue o mesmo padrão de `black`

      - id: flake8
        name: Lint code with Flake8
        entry: poetry run flake8
        language: system
        types: [python]
        args: ['--max-line-length=88']

      - id: mypy
        name: Type check with MyPy
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: true

      - id: safety
        name: Check dependencies for security issues
        entry: poetry run safety check --full-report --file=requirements.txt --file=requirements_dev.txt
        language: system
        pass_filenames: false

      - id: check-added-large-files
        name: Prevent large files in repo
        entry: >
          poetry run python -c "import sys, os;
          [print(f'File too large: {f}') or sys.exit(1) for f in sys.argv[1:] if os.path.getsize(f) > 500 * 1024]"
        language: system
        pass_filenames: true
